@startuml
start
:Студент создаёт мероприятие;
:Статус: На проверке;
:Куратор проверяет;
if (Решение) then (Одобрить)
  :Проставить баллы 1-5;
  :Статус: Одобрено;
else (Отклонить)
  :Статус: В комиссии;
  :Комиссия рассматривает;
  if (Арбитраж) then (Подтвердить отказ)
    :Статус: Отклонено;
  elseif (Отменить отказ)
    :Статус: Одобрено + баллы;
  else (Вернуть)
    :Статус сброшен;
    :На проверку;
  endif
endif
stop
@enduml
